"""Added  new table to my database

Revision ID: 1dc724760697
Revises: e0cb99368a05
Create Date: 2024-02-26 10:31:44.210130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc724760697'
down_revision = 'e0cb99368a05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_us', schema=None) as batch_op:
        batch_op.alter_column('Message',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.String(length=10000),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('contact_us', schema=None) as batch_op:
        batch_op.alter_column('Message',
               existing_type=sa.String(length=10000),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###
