"""added one more 

Revision ID: 4567c909e550
Revises: 6c80c30db644
Create Date: 2024-03-05 23:50:11.277378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4567c909e550'
down_revision = '6c80c30db644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruit',
    sa.Column('Fruit', sa.String(length=100), nullable=False),
    sa.Column('disease', sa.String(length=1000), nullable=False),
    sa.Column('fruit_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('fruit_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fruit')
    # ### end Alembic commands ###
