"""changing the size of columns in fertilizer table

Revision ID: 6c80c30db644
Revises: e111833be96a
Create Date: 2024-03-04 19:26:59.079491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c80c30db644'
down_revision = 'e111833be96a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.alter_column('disease',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1000),
               existing_nullable=False)
        batch_op.alter_column('Fertilizers',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.alter_column('Fertilizers',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('disease',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
