"""deleted one coloumn

Revision ID: ac41ac65e6a5
Revises: 4567c909e550
Create Date: 2024-03-05 23:55:50.556480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac41ac65e6a5'
down_revision = '4567c909e550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fertilizers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizers',
    sa.Column('Fruit', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('disease', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('fruit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fruit_id', name='fertilizers_pkey')
    )
    # ### end Alembic commands ###
