"""added one more table

Revision ID: c39aa7350c53
Revises: ac41ac65e6a5
Create Date: 2024-03-06 00:03:43.208669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c39aa7350c53'
down_revision = 'ac41ac65e6a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fruit_disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fruit_disease_id'], ['fruit.fruit_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fertilizer')
    # ### end Alembic commands ###
