"""added another table

Revision ID: e111833be96a
Revises: f56d1d6d7ec8
Create Date: 2024-03-04 09:31:50.929503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e111833be96a'
down_revision = 'f56d1d6d7ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fertilizer_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('fertilizers', schema=None) as batch_op:
        batch_op.drop_column('fertilizer_id')

    # ### end Alembic commands ###
