"""added another table

Revision ID: f56d1d6d7ec8
Revises: 1dc724760697
Create Date: 2024-03-04 09:28:55.687703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56d1d6d7ec8'
down_revision = '1dc724760697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizers',
    sa.Column('Fruit', sa.String(length=100), nullable=False),
    sa.Column('disease', sa.String(length=120), nullable=False),
    sa.Column('Fertilizers', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('Fruit')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fertilizers')
    # ### end Alembic commands ###
